CC=gcc
STDFLAGS=-Wall -Werror -Wextra -std=c11 #-fsanitize=address
TST_CFLAGS:= -g $(STDFLAGS)
GCOV_FLAGS?=-fprofile-arcs -ftest-coverage
LINUX_FLAGS=-lsubunit -lrt -lpthread -lm
LIBS=-lcheck
VALGRIND_FLAGS=--trace-children=yes --track-fds=yes --track-origins=yes --leak-check=full --show-leak-kinds=all --verbose

flafs_c			=-Wall -Werror -Wextra -std=c11
# flags_check=-lcheck
flags_check		=$(shell pkg-config --libs check)
flags_gcov		=--coverage
flags_sanitize	=#-fsanitize=address -static-libasan -g
flags_valgrid	=	CK_FORK=no valgrind --trace-children=yes \
					--track-fds=yes --leak-check=full \
					--track-origins=yes --log-file=valgrind-out.txt --show-leak-kinds=all
TEST_FILES = $(wildcard backend/tests/*.c)
SRC_FILES = $(wildcard backend/*.c)

dir_tests		= gui/backend/tests/
dir_calc_src	= gui/backend/
dir_build		= ../build
static_lib 		= s21_SmartCalc.a
dir_qt 			= gui
qt_project_name = ../build/
DIRECTORY 		= gui/
ifeq ($(shell uname), Linux)
	flafs_c		+= -U__STRICT_ANSI__
	flags_check +=-lpthread -lrt -lsubunit -lm
endif

all: install run

#install:
#	cd gui/ && cmake $(CURDIR)/gui && make
install:
	cmake -S gui/. -B ../build
	cmake --build ../build --target SmartCalc --config Release  --clean-first

run:
	../build/SmartCalc

uninstall:
	rm -rf ../build


dist: install
	[ -d ../$(qt_project_name) ] || mkdir -p ../$(qt_project_name)
	cp -r ../build/* ../$(qt_project_name)/
	tar cvzf ../SmartCalc_v1.0.tgz -C ../ $(qt_project_name)
	rm -rf ../$(qt_project_name)
	#make uninstall

dvi:

	open html/index.html

test: #clean
	cmake -S gui/. -B ../build/tests
	cmake --build ../build/tests --target Back_test --config Release  --clean-first

gcov_report: clean
	$(CC) $(STDFLAGS) $(GCOV_FLAGS)  $(TEST_FILES) $(SRC_FILES) -o Back_test $(LIBS) $(LINUX_FLAGS)
	./Back_test
	gcov *.gcda
	gcovr --html-details -o report.html
	open report.html

clean:
	rm -rf a.out  Back_test unit_test gcov_test *.gcda *.gcno *.gcov *.info ${static_lib} *.o  test.c valgrind-out.txt *.css
clean_all: clean
	rm -rf report test main $(dir_qt)/build-smart_calc ../SmartCalc_v1.0.tgz $(dir_qt)/build-sm_clc-Desktop-Debug  report*.html

fix_clang_format:
	clang-format -i *.cpp  gui/*.cpp gui/*.h backend/*.c backend/*.h backend/tests/*.c backend/tests/*.h
	rm -f .clang-format